version: '3.4'

services:
  bibemmovimento-frontend:
    image: biblioteca-em-movimento-estatico:latest
    build:
      context: ./Biblioteca-Em-Movimento-Estatico
    depends_on:
      - bibemmovimento-backend
    ports:
      - "80:80"  
    networks: 
      - bibemmovimento-network
  bibemmovimento-backend:
    image: andreyevyk/bibemmovimento
    build:
      context: ./BibEmMovimento-BackEnd
    ports:
      - "4000:80"  
    networks: 
      - bibemmovimento-network


  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=xLsnKiLkqFse
      - MYSQL_DATABASE=BibEmMovimento
  adminer:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 3000:80
    depends_on: 
      - db
    environment:
      - PMA_ARBITRRY=1
    networks: 
      - bibemmovimento-network

networks: 
  bibemmovimento-network:
    driver: bridge