// <auto-generated />
using BibEmMovimento.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BibEmMovimento.Migrations
{
    [DbContext(typeof(BibEmMovimentoContext))]
    [Migration("20190705015207_criação banco de dados")]
    partial class criaçãobancodedados
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BibliotecaEmMovimento.Models.PageContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Add_Info");

                    b.Property<string>("Content");

                    b.Property<string>("Image_src");

                    b.Property<int>("Page");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("PageContent");
                });
#pragma warning restore 612, 618
        }
    }
}
